import React, { FC, useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import SideBar from '../../../shared/adminComponents/SideBar/SideBar';
import Header from '../../../shared/adminComponents/Header/Header';
import ProductsComponent from '../../../shared/adminComponents/ProductsComponent/ProductsComponent';
import Dropdown from '../../../shared/adminComponents/Dropdown';


interface Product {
  id: number;
  name: string;
  restaurantName: string;
  price: number;
  path: string;
}

const Product: Product[] = [
  {
    id: 1,
    name: 'Marqarita',
    restaurantName: 'Papa Johns',
    price: 16,
    path: '/adminImg/ProductsPage/Pizza.svg',
  },
  {
    id: 2,
    name: 'Marqarita',
    restaurantName: 'Mc Donalds',
    price: 1116,
    path: '/adminImg/ProductsPage/Pizza.svg',
  },
  {
    id: 3,
    name: 'Marqarita',
    restaurantName: 'Burger King',
    price: 1236,
    path: '/adminImg/ProductsPage/Pizza.svg',
  },
  {
    id: 4,
    name: 'Marqarita',
    restaurantName: 'Mc Donalds',
    price: 126,
    path: '/adminImg/ProductsPage/Pizza.svg',
  },
  {
    id: 5,
    name: 'Marqarita',
    restaurantName: 'Burger King',
    price: 312,
    path: '/adminImg/ProductsPage/Pizza.svg',
  }
  ,
  {
    id: 6,
    name: 'Marqarita',
    restaurantName: 'Kfc',
    price: 20,
    path: '/adminImg/ProductsPage/Pizza.svg',
  }
];

const AdminProducts: NextPage = () => {
  const [activeData, setActiveData] = useState<Product[]>(Product);

  const deleteProduct = (id: number | string): void => {
    setActiveData(activeData.filter((item) => item.id !== id));
  };

  const filterProduct = (title: Product): void => {
    // let newData = activeData.filter((item) => item.restaurantName == title)
    // setActiveData(newData)
    console.log(title);
    
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-[19px] min-h-screen bg-[#1E1E30] relative">
        <Header />
        <div className="flex gap-x-4">
          <SideBar />
          <div className="flex flex-col w-full">
            <div className="flex justify-between px-8 py-5 bg-[#27283c] mb-[52px] rounded-lg">
              <h3 className="text-[#C7C7C7] text-xl font-semibold">Products</h3>
              <Dropdown
                filterItems={filterProduct}
                items={["Papa Johns", "Kfc", "Mc Donalds", "Burger King"]}
                className={"flex bg-[#5A5B70] rounded-[14px] px-[18px] py-2 relative w-[199px]"}
              />
            </div>
            <div className="flex gap-x-10 gap-y-10 flex-wrap justify-between">
              {activeData.map((item) => (
                <ProductsComponent
                  detail={item}
                  deleteProduct={deleteProduct}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminProducts;








