import type { NextPage } from "next";
import Head from "next/head";
import Dashboard from "./dashboard";
import Header from "../../shared/adminComponents/Header/Header";
import SideBar from "../../shared/adminComponents/SideBar/SideBar";

const AdminDashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next Ap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <SideBar/>
    </div>
  );
};

export default AdminDashboard;