import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";

const AdminDashboard: NextPage = () => {
  const { push } = useRouter()
  useEffect(() => {
    push("/Admin/Dashboard")
  },[])
  return (
    <div>
      <Head>
        <title>Create Next Ap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default AdminDashboard;