import type { NextPage } from "next";
import Head from "next/head";
import LoginPage from "../../../shared/adminComponents/LoginPage/LoginPage";

const Login: NextPage = () => {
  return (
    <div className="bg-[#1E1E30] min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />

    </div>
  );
};

export default Login;
