import type { NextPage } from "next";
import Head from "next/head";
import SideBar from "../../../shared/adminComponents/SideBar/SideBar";
import Header from "../../../shared/adminComponents/Header/Header";
import RestaurantComponent from "../../../shared/adminComponents/RestaurantComponent/RestaurantComponent";


const AdminRestaurants: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-[19px] min-h-screen bg-[#1E1E30]">
        <Header
         />
        <div className='flex gap-x-4'>
          <SideBar/>
          <div className="flex flex-col w-full">
            <div className="flex justify-between px-8 py-5 bg-[#27283c] mb-[52px] rounded-lg">
              <h3 className="text-[#C7C7C7] text-xl font-semibold">Products</h3>
            <div className="flex gap-x-10">
                <div className="flex justify-between items-center w-[199px] h-[35px] bg-[#5A5B70] rounded-[14px] px-[18px] py-[4px]">
                  <span className="text-[#C7C7C7] text-[14px] font-semibold">Restaurant Type</span>
                  <img src="/adminImg/RestaurantPage/ArrowDown.svg" alt="" />
                </div>
                <div className="w-[168px] h-[35px] bg-fuchsia-700 rounded-[14px] shadow border-2 border-fuchsia-700 flex items-center p-2">
                  <img src="/adminImg/RestaurantPage/Plus.svg" alt="Plus" />
                  <span className="w-[137px] h-5 text-center text-white text-sm font-bold tracking-tight">ADD RESTAURANT </span>
                </div>
            </div>
            </div>
          <div className="flex gap-x-10 gap-y-10 flex-wrap">
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
            <RestaurantComponent />
          </div>
         
        </div>
      </div>
    </div>
    </div>
 
  );
};

export default AdminRestaurants;
