import Image from "next/image";
import Header from "../../shared/components/Header/index";

import Head from "next/head";

const NotFound = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex p-[30px]">
          <Image
            src="/client/404/404.svg"
            alt="404"
            width={1373}
            height={727}
            className="w-full h-[727px] object-contain"
          />
      </main>
    </div>
  );
};

export default NotFound;
