import Header from "../../shared/components/Header/index";
import Footer from "../../shared/components/Footer";

import Image from "next/image";
import Head from "next/head";

const NotFound = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
          isLogin={true}
          isBasket={true}
          isAvatar={true}
          isName={false}
          isBottom={false}
      />

      <main className="flex p-[30px]">
          <Image
            src="/client/404/404.svg"
            alt="404"
            width={1373}
            height={727}
            className="w-full h-[727px] object-contain"
          />
      </main>

      <Footer
          isTop={false}
      />
    </div>
  );
};

export default NotFound;
