import type { NextPage } from "next";
import Head from "next/head";

const AdminCategory: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Admin Category</h1>
    </div>
  );
};

export default AdminCategory;
